name: pocketbase_ui
description: A new Flutter package project.
version: 0.0.2
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.2.1
  platform_info: ^4.0.2
  pocketbase: ">=0.15.0 <1.0.0"
  signals: ">=4.0.0"
  timeago: ^3.6.0
  url_launcher: ^6.2.0
  sqlite_storage_pocketbase:
    git:
      url: https://github.com/rodydavis/sqlite_storage
      path: packages/sqlite_storage_pocketbase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.3

flutter:
