name: pocketbase_ui
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^1.2.1
  platform_info: ^4.0.2
  pocketbase: ">=0.15.0 <1.0.0"
  signals: ">=2.0.0 <3.0.0"
  timeago: ^3.6.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^3.2.3

flutter:
